# Site settings
title: Rosie Van Alsburg
email: roseva@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi it is Rosie, I code and do space stuff
baseurl: "/home" 
url: "/" # the base hostname & protocol for your site
twitter_username: rosieintech
github_username:  roseva
gitlab_username:  roseva
